on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <dev|staging|prod>"
        required: true
        default: "dev"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.11.0
        with:
          apiToken: ${{ secrets.OSRESS_CLOUDFLARE_API_TOKEN }}
          command: deploy --env ${{ github.event.inputs.environment }}
